# Generated by Django 3.0.5 on 2020-12-01 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201201_0531'),
        ('restaurant', '0002_auto_20201130_0742'),
        ('order', '0003_auto_20201130_0725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='order',
            new_name='cart',
        ),
    ]
