# Generated by Django 3.0.5 on 2020-11-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='section',
        ),
        migrations.AddField(
            model_name='dish',
            name='section',
            field=models.ManyToManyField(to='menu.Section'),
        ),
    ]
