# Generated by Django 3.0.5 on 2020-12-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201130_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='allergens',
        ),
    ]
