# Generated by Django 3.0.5 on 2020-11-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='United States', max_length=100)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'Newhampshire'), ('NJ', 'Newjersey'), ('NM', 'Newmexico'), ('NY', 'Newyork'), ('NC', 'Northcarolina'), ('ND', 'Northdakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhodeisland'), ('SC', 'Southcarolina'), ('SD', 'Southdakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'Westvirginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('city', models.CharField(default='Baton Rouge', max_length=85)),
                ('county', models.CharField(default='East Baton Rouge', max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('zipcode', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
            ],
        ),
    ]
