# Generated by Django 3.0.5 on 2020-11-30 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
